# Generated by Django 3.0.5 on 2020-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='code',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('present', 'Present')], max_length=250),
        ),
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
