# Generated by Django 3.0.5 on 2020-10-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20201029_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together={('name', 'grade')},
        ),
    ]
