# Generated by Django 3.0.5 on 2020-10-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201029_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together={('name', 'grade', 'deleted')},
        ),
    ]
