# Generated by Django 3.0.5 on 2020-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20201029_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'day')},
        ),
    ]
