# Generated by Django 3.0.5 on 2020-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20201029_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='report',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=250),
        ),
    ]
